name: Run Tests + Coverage on PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --no-restore --configuration Release

      # Produces coverage.cobertura.xml under **/TestResults/**/
      - name: Test with coverage (XPlat Code Coverage)
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      # Optional: show where the coverage file(s) are
      - name: Debug - list coverage files
        run: |
          echo "Searching for coverage.cobertura.xml..."
          find . -type f -name "coverage.cobertura.xml" -print

      - name: Install ReportGenerator tool
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Generate nice HTML from all Cobertura reports (handle multiple test projects too)
      - name: Generate HTML coverage report
        run: |
          reportgenerator \
            -reports:"**/TestResults/**/coverage.cobertura.xml" \
            -targetdir:"CoverageReport" \
            -reporttypes:Html

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: CoverageReport
